import React, { createContext, useState, useContext } from 'react';

// Create the language context
export const LanguageContext = createContext();

// Translations for various languages
const translations = {
  en: {
    welcome: "Welcome to Mood Music",
    getStarted: "Get Started",
    home: "Home",
    search: "Search",
    settings: "Settings",
    moodSelector: "Mood Selector",
    play: "Play",
    pause: "Pause",
    next: "Next",
    prev: "Previous",
    games: "Games",
    playlist: "Playlist",
    moodQuotes: "Mood Quotes",
    audioTherapy: "Audio Therapy",
    moodTracker: "Mood Tracker",
  },
  es: {
    welcome: "Bienvenido a Mood Music",
    getStarted: "Comenzar",
    home: "Inicio",
    search: "Buscar",
    settings: "Configuraciones",
    moodSelector: "Selector de ánimo",
    play: "Reproducir",
    pause: "Pausa",
    next: "Siguiente",
    prev: "Anterior",
    games: "Juegos",
    playlist: "Lista de reproducción",
    moodQuotes: "Citas de ánimo",
    audioTherapy: "Terapia de audio",
    moodTracker: "Rastreador de ánimo",
  },
  hi: {
    welcome: "मूड म्यूजिक में आपका स्वागत है",
    getStarted: "शुरू करें",
    home: "घर",
    search: "खोज",
    settings: "सेटिंग्स",
    moodSelector: "मूड चयनकर्ता",
    play: "चलाएं",
    pause: "रोकें",
    next: "अगला",
    prev: "पिछला",
    games: "खेल",
    playlist: "प्लेलिस्ट",
    moodQuotes: "मूड उद्धरण",
    audioTherapy: "ऑडियो थेरेपी",
    moodTracker: "मूड ट्रैकर",
  },
  te: {
    welcome: "మూడ్ మ్యూజిక్‌కు స్వాగతం",
    getStarted: "ప్రారంభించండి",
    home: "హోమ్",
    search: "వెతకండి",
    settings: "సెట్టింగ్స్",
    moodSelector: "మూడ్ సెలెక్టర్",
    play: "ప్లే",
    pause: "పాజ్",
    next: "తరువాత",
    prev: "మునుపటి",
    games: "గేమ్స్",
    playlist: "ప్లేలు",
    moodQuotes: "మూడ్ కోట్స్",
    audioTherapy: "ఆడియో థెరపీ",
    moodTracker: "మూడ్ ట్రాకర్",
  },
  de: {
    welcome: "Willkommen bei Mood Music",
    getStarted: "Loslegen",
    home: "Zuhause",
    search: "Suche",
    settings: "Einstellungen",
    moodSelector: "Stimmungsauswahl",
    play: "Abspielen",
    pause: "Pause",
    next: "Nächster",
    prev: "Vorheriger",
    games: "Spiele",
    playlist: "Wiedergabeliste",
    moodQuotes: "Stimmungszitate",
    audioTherapy: "Audio-Therapie",
    moodTracker: "Stimmungsverfolger",
  },
  ta: {
    welcome: "மூட் மியூசிக்குக்குச் சுவாகதம்",
    getStarted: "துவக்கவும்",
    home: "வீடு",
    search: "தேடுங்கள்",
    settings: "அமைப்புகள்",
    moodSelector: "மூட் தேர்வு",
    play: "பிளே",
    pause: "நிறுத்தவும்",
    next: "அடுத்தது",
    prev: "முந்தைய",
    games: "விளையாட்டுகள்",
    playlist: "பிளேலிஸ்ட்",
    moodQuotes: "மூட் குவோட்டுகள்",
    audioTherapy: "ஆடியோ சிகிச்சை",
    moodTracker: "மூட் டிராக்கர்",
  },
  fr: {
    welcome: "Bienvenue dans Mood Music",
    getStarted: "Commencer",
    home: "Accueil",
    search: "Recherche",
    settings: "Paramètres",
    moodSelector: "Sélecteur d'humeur",
    play: "Jouer",
    pause: "Pause",
    next: "Suivant",
    prev: "Précédent",
    games: "Jeux",
    playlist: "Liste de lecture",
    moodQuotes: "Citations d'humeur",
    audioTherapy: "Thérapie par audio",
    moodTracker: "Suivi de l'humeur",
  },
  it: {
    welcome: "Benvenuto in Mood Music",
    getStarted: "Iniziare",
    home: "Casa",
    search: "Cerca",
    settings: "Impostazioni",
    moodSelector: "Selettore di umore",
    play: "Gioca",
    pause: "Pausa",
    next: "Successivo",
    prev: "Precedente",
    games: "Giochi",
    playlist: "Playlist",
    moodQuotes: "Citazioni dell'umore",
    audioTherapy: "Terapia audio",
    moodTracker: "Tracciatore d'umore",
  },
  pt: {
    welcome: "Bem-vindo ao Mood Music",
    getStarted: "Começar",
    home: "Casa",
    search: "Pesquisar",
    settings: "Configurações",
    moodSelector: "Seletor de humor",
    play: "Tocar",
    pause: "Pausar",
    next: "Próximo",
    prev: "Anterior",
    games: "Jogos",
    playlist: "Playlist",
    moodQuotes: "Citações de humor",
    audioTherapy: "Terapia de áudio",
    moodTracker: "Rastreador de humor",
  },
  ja: {
    welcome: "ムードミュージックへようこそ",
    getStarted: "始める",
    home: "ホーム",
    search: "検索",
    settings: "設定",
    moodSelector: "ムードセレクター",
    play: "再生",
    pause: "一時停止",
    next: "次",
    prev: "前",
    games: "ゲーム",
    playlist: "プレイリスト",
    moodQuotes: "ムード引用",
    audioTherapy: "オーディオセラピー",
    moodTracker: "ムードトラッカー",
  },
  zh: {
    welcome: "欢迎来到 Mood Music",
    getStarted: "开始",
    home: "主页",
    search: "搜索",
    settings: "设置",
    moodSelector: "情绪选择器",
    play: "播放",
    pause: "暂停",
    next: "下一首",
    prev: "上一首",
    games: "游戏",
    playlist: "播放列表",
    moodQuotes: "情绪引用",
    audioTherapy: "音频疗法",
    moodTracker: "情绪追踪器",
  },
  ar: {
    welcome: "مرحبًا بك في Mood Music",
    getStarted: "ابدأ",
    home: "الصفحة الرئيسية",
    search: "بحث",
    settings: "الإعدادات",
    moodSelector: "محدد المزاج",
    play: "تشغيل",
    pause: "إيقاف مؤقت",
    next: "التالي",
    prev: "السابق",
    games: "الألعاب",
    playlist: "قائمة التشغيل",
    moodQuotes: "اقتباسات المزاج",
    audioTherapy: "علاج الصوت",
    moodTracker: "تتبع المزاج",
  },
};

// LanguageProvider component to provide the language state
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en'); // Default language is English

  const setLang = (lang) => {
    setLanguage(lang); // Update the language
  };

  // Fetch the translation for the selected language
  const getTranslation = (key) => {
    return translations[language][key] || key; // Return key if no translation found
  };

  return (
    <LanguageContext.Provider value={{ setLang, getTranslation }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook to use the language context
export const useLanguage = () => {
  return useContext(LanguageContext);
};
